require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FranchisesController do

  # This should return the minimal set of attributes required to create a valid
  # Franchise. As you add validations to Franchise, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all franchises as @franchises" do
      franchise = Franchise.create! valid_attributes
      get :index
      assigns(:franchises).should eq([franchise])
    end
  end

  describe "GET show" do
    it "assigns the requested franchise as @franchise" do
      franchise = Franchise.create! valid_attributes
      get :show, :id => franchise.id.to_s
      assigns(:franchise).should eq(franchise)
    end
  end

  describe "GET new" do
    it "assigns a new franchise as @franchise" do
      get :new
      assigns(:franchise).should be_a_new(Franchise)
    end
  end

  describe "GET edit" do
    it "assigns the requested franchise as @franchise" do
      franchise = Franchise.create! valid_attributes
      get :edit, :id => franchise.id.to_s
      assigns(:franchise).should eq(franchise)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Franchise" do
        expect {
          post :create, :franchise => valid_attributes
        }.to change(Franchise, :count).by(1)
      end

      it "assigns a newly created franchise as @franchise" do
        post :create, :franchise => valid_attributes
        assigns(:franchise).should be_a(Franchise)
        assigns(:franchise).should be_persisted
      end

      it "redirects to the created franchise" do
        post :create, :franchise => valid_attributes
        response.should redirect_to(Franchise.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved franchise as @franchise" do
        # Trigger the behavior that occurs when invalid params are submitted
        Franchise.any_instance.stub(:save).and_return(false)
        post :create, :franchise => {}
        assigns(:franchise).should be_a_new(Franchise)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Franchise.any_instance.stub(:save).and_return(false)
        post :create, :franchise => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested franchise" do
        franchise = Franchise.create! valid_attributes
        # Assuming there are no other franchises in the database, this
        # specifies that the Franchise created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Franchise.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => franchise.id, :franchise => {'these' => 'params'}
      end

      it "assigns the requested franchise as @franchise" do
        franchise = Franchise.create! valid_attributes
        put :update, :id => franchise.id, :franchise => valid_attributes
        assigns(:franchise).should eq(franchise)
      end

      it "redirects to the franchise" do
        franchise = Franchise.create! valid_attributes
        put :update, :id => franchise.id, :franchise => valid_attributes
        response.should redirect_to(franchise)
      end
    end

    describe "with invalid params" do
      it "assigns the franchise as @franchise" do
        franchise = Franchise.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Franchise.any_instance.stub(:save).and_return(false)
        put :update, :id => franchise.id.to_s, :franchise => {}
        assigns(:franchise).should eq(franchise)
      end

      it "re-renders the 'edit' template" do
        franchise = Franchise.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Franchise.any_instance.stub(:save).and_return(false)
        put :update, :id => franchise.id.to_s, :franchise => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested franchise" do
      franchise = Franchise.create! valid_attributes
      expect {
        delete :destroy, :id => franchise.id.to_s
      }.to change(Franchise, :count).by(-1)
    end

    it "redirects to the franchises list" do
      franchise = Franchise.create! valid_attributes
      delete :destroy, :id => franchise.id.to_s
      response.should redirect_to(franchises_url)
    end
  end

end
